### ISSUE TITLE
Alignment problem of buffer_storage_t as function parameter in Visual Studio 2015 Win32

### ISSUE THREAD

**Issue by binglongx** [Stiffstream/restinio#1]
Building [minimalistic hello world](https://stiffstream.com/en/docs/restinio/0.4/gettingstarted.html#minimalistic-hello-world) sample results in errors like:

>message_builders.hpp(182): error C2719: 'body': formal parameter with requested alignment of 8 won't be aligned

This is because buffer_storage_t is decorated with **alignas( std::max_align_t )**. It seems that there is no easy way to bypass this in VS 2015, which does not support aligned function arguments. 

Commenting out **alignas( std::max_align_t )** in Lines 86 and 211 in *buffers.hpp*, the sample works for VS 2015. I am however unsure about the impact of removing the alignment requirement. 

Is conditional compilation to handle VS2015 acceptable in this case? What is your opinion? Thanks.

**Comment by eao197** [comment]
We can make workaround similar to one from [timertt](https://sourceforge.net/p/sobjectizer/repo/HEAD/tree/tags/timertt/1.2.2/dev/timertt/all.hpp#l34) library. It will  work for VS2015 builds on x32/x64 platforms.

**Comment by binglongx** [comment]
I tried replacing **alignas( std::max_align_t )** with **__declspec(align(8))** in the two aformentioned lines in *buffers.hpp*. For VS2015 Win32 builds, it chokes with exactly the same errors. VS2015 (Win32 builds) just cannot honor aligned function parameters. VS2015 (x64 builds) however always compiles fine.

I think **TIMERTT_ALIGNAS_WORKAROUND** in SObjectizer/[timertt](https://sourceforge.net/p/sobjectizer/repo/HEAD/tree/tags/timertt/1.2.2/dev/timertt/all.hpp#l34) library should have similar problems with VS2015 Win32 builds.

**Comment by binglongx** [comment]
Just tested on VS2017, both x86 and x64 builds work fine. So the issue is specific to x86 builds in VS2015 (and probably prior versions).

**Comment by eao197** [comment]
Which version of VS2015's compiler do you have?

I'm trying version 19.00.24210 now and it supports `alignas` and `alignof` keywords.
This version also compiles sobjectizer/timertt cleanly.

**Comment by ngrodzitski** [comment]
@binglongx, please, check out v.0.4.0.1 (or current master), it has fixes for the issue.
