### ISSUE TITLE
Where is the http client module?

### ISSUE THREAD

**Issue by cdsama** [Stiffstream/restinio#10]
Your code is absolutely awesome, its really what I need.And I found that it seems no http client module or not documented. How to communicate with other servers? Do I need another http client library?

**Comment by eao197** [comment]
Hi!

There is no http-client in the RESTinio. RESTinio was started as an attempt to implement an embedded async HTTP/WebSocket server for modern C++ application (with emphasis on *async*). Maybe client-part will be implemented somewhere in the future but we don't know when.

If you want to implement a service that handles incoming HTTP-requests and produces some outgoing HTTP-requests you have to use some HTTP-client library. Like libcurl. Some explanations of how it can be done can be found [here](https://eao197.blogspot.com/2018/03/progc-async-processing-of-incoming-and.html).

**Comment by cdsama** [comment]
@eao197 Thanks for your reply, I would consider integrate a HTTP-client library in my project.
