### ISSUE TITLE
Single Header File Install?

### ISSUE THREAD

**Issue by scm-ns** [Stiffstream/restinio#104]
Is there a way to get a single header file for the project? So that I just need to add that header to my source tree and be done with it? 

I think that will make this project much more easier to include! 

Thanks!

**Comment by eao197** [comment]
> Is there a way to get a single header file for the project?

No. And we have no plan to go into that direction because there are some reasons to not do that.

> I think that will make this project much more easier to include!

I hope that wide spreading of tools like *vcpkg* and *conan* will make that even easier.

**Comment by scm-ns** [comment]
Thanks!
