### ISSUE TITLE
Missing inline ?

### ISSUE THREAD

**Issue by Ozomahtli** [Stiffstream/restinio#105]
Hey!
I'm getting duplicate symbol warning when linking, due a missing `inline` here:
https://github.com/Stiffstream/restinio/blob/c34f83a68e60537eba52e2d076ed22495ad4c5df/dev/restinio/utils/base64.hpp#L250

Thanks,

**Comment by eao197** [comment]
Thanks for reporting this. The fix is in the master branch now.

**Comment by eao197** [comment]
The fix is a part of v.0.6.8.1 released today.

**Comment by Ozomahtli** [comment]
Thanks!
