### ISSUE TITLE
[CMake] Missing "project" command

### ISSUE THREAD

**Issue by MikeGitb** [Stiffstream/restinio#106]
Unless I'm overlooking something (which is perfectly possible), the cmake list file(s) is missing a project command, which leads to warnings when building with cmake :

	CMake Warning (dev) in [....]\restinio\dev\CMakeLists.txt:
	  No project() command is present.  The top-level CMakeLists.txt file must
	  contain a literal, direct call to the project() command.  Add a line of
	  code such as

		project(ProjectName)

	  near the top of the file, but after cmake_minimum_required().

	  CMake is pretending there is a "project(Project)" command on the first
	  line.
	This warning is for project developers.  Use -Wno-dev to suppress it.

Is there a particular reason for that?

**Comment by eao197** [comment]
> Is there a particular reason for that?

Perhaps the main reason is that we almost do not use CMake for ourselves. So there could be some flaws in CMakeList.txt files.

**Comment by eao197** [comment]
The fix for that will be a part of upcoming v.0.6.9.

**Comment by MikeGitb** [comment]
Thanks
