### ISSUE TITLE
Sharing TLS context between application and restinio

### ISSUE THREAD

**Issue by prince-chrismc** [Stiffstream/restinio#123]
### Use Case

I am investigating how to support [RFC7030](https://tools.ietf.org/html/rfc7030) in my application, the runtime/dynamic changing of certificates and keys forces me to have access to the OpenSSL `SSL_CTX*` context or `asio::ssl::context`.

### Issue

The  challenge is the restinio API forces me to move the SSL context losing reference to it. Internally however, everything is supported with a `shared_ptr` to the `tls_context`.

https://github.com/Stiffstream/restinio/blob/0ef04a26155d8aa4a56a36cc013c7e722675da21/dev/restinio/tls.hpp#L254

### Potential Solution

Would it be possible to expanding the restinio API to allow for `socket_type_dependent_settings_t< Settings, tls_socket_t >` to support a `shared_ptr` to a `tls_context`?

https://github.com/Stiffstream/restinio/blob/bd4382c2fd355efa8ee2f1fffe62f0134b472e30/dev/restinio/tls.hpp#L227

Changing ...

```diff
-asio_ns::ssl::context m_tls_context{ asio_ns::ssl::context::sslv23 };
+std::shared_ptr<asio_ns::ssl::context> m_tls_context = std::make_shared(asio_ns::ssl::context::sslv23)
```

Along with adding a new overload for `Settings& tls_context(shared_ptr<...>)`

The API break would be the on the `tls_contect()` which would need to return a shared tls context... however since this is a move I would not expect anyone to be using it. Calling this in the application would prevent the `http_server` from starting.

I would love to open a PR for this if you are interested in the API break :smile:

**Comment by eao197** [comment]
There are several changes in dev branch 0.6-dev-0.6.10:

`std::shared_ptr<asio::ssl::context>` is now stored in `socket_type_dependent_settings_t`

a couple of new overloads in `socket_type_dependent_settings_t`:
https://github.com/Stiffstream/restinio/blob/bac11ec9cd08e3d1ebe663a9be17f0808e74d7af/dev/restinio/tls.hpp#L246-L292

a new method in `socket_type_dependent_settings_t` that is used in the constructor of `socket_supplier_t<tls_socket_t>` 
https://github.com/Stiffstream/restinio/blob/bac11ec9cd08e3d1ebe663a9be17f0808e74d7af/dev/restinio/tls.hpp#L317-L321

a new example that shows how shared TLS-context can be used: https://github.com/Stiffstream/restinio/blob/0.6-dev-0.6.10/dev/sample/shared_tls_context/main.cpp

That all is a part of dev branch now, but I think I'll release v.0.6.10 in a couple of next days.

**Comment by prince-chrismc** [comment]
:heart: That's exactly what I was imagining! My teams has an event at the end of the month, I can assure you we will be using this in the coming days.

Greatly appreciated!

**Comment by prince-chrismc** [comment]
Just tested 0.6.10, this worked perfectly! :100: better than expected :heart:
