### ISSUE TITLE
How to send back Html file

### ISSUE THREAD

**Issue by noctera** [Stiffstream/restinio#130]
I want to send a Html file to the user

```
router->http_get(
		"/html",
		[]( auto req, auto ){
				init_resp( req->create_response() )
						.append_header( restinio::http_field::content_type, "text/html; charset=utf-8" )
						.set_body(restinio::sendfile( "./adminPanel/index.html" ))
						.done();

				return restinio::request_accepted();
		} );
```
but the console is always telling me
```
[2020-11-21 17:03:56.494] ERROR: [connection:2] error while handling request: unable to openfile './adminPanel/index.html': No such file or directory
```
Could someone help me?
The html file is located in ```./adminPanel/index.html```

**Comment by eao197** [comment]
Hi!

Try to specify the absolute path as a parameter for `sendfile`. If it will work then you have to check the current directory for your process.

**Comment by noctera** [comment]
I got it running with the absolute path, but somehow, when specifying the path of the current directory, it does not work

**Comment by noctera** [comment]
Ok solved it. Somehow it worked with
```
"../src/adminPanel/index.html"```
I had to get out of the directory and cd into it again. Strange but luckily it solved the problem.
Thanks for your help :)
