### ISSUE TITLE
http_parser no longer maintained

### ISSUE THREAD

**Issue by seghcder** [Stiffstream/restinio#132]
Doing some dependency updates and saw this - https://github.com/nodejs/http-parser/issues/522:

> I'm moving on and as the last (semi-)active maintainer, that means http-parser is now effectively unmaintained.
> It's a stable project for a stable protocol and I don't expect many issues but you should take the above into account when evaluating whether http-parser is the right choice for you.
> For new projects and projects looking to migrate, I recommend https://github.com/nodejs/llhttp. Similar API, feature parity, well maintained and in active use.

Perhaps important given the security context here - https://github.com/Stiffstream/restinio/issues/109#issuecomment-651978009

Per the quote, it's probably not an immediate concern but something to potentially factor into 0.7x thinking?

**Comment by eao197** [comment]
Hi! Thanks for reporting this!

I didn't know about http-parser maintenance problems. It's a pity.

However, it opens at least two possibilities: one is the switching to an alternative (like llhttp mentioned above, or [picohttpparser](https://github.com/h2o/picohttpparser), or something else), another is to develop our own header-only HTTP-parser (by using restinio::easy_parser that can simplify such task significantly). And if we want to move to support not only HTTP/1.1, but also HTTP/2 and HTTP/3, the own parser may be a good scenario to go.

Anyway, I have to spend the nearest week or two to close some SObjectizer-related tasks. Hope to return back to RESTinio after that.

It leaves some time for me to think about choices.

PS. The morning sun never lasts the day. :(

**Comment by eao197** [comment]
llhttp is used since v.0.7.0
