### ISSUE TITLE
Compilation errors when building the library as a part of the build tree of the project

### ISSUE THREAD

**Issue by micnekr** [Stiffstream/restinio#137]
I am using CLion to compile from the IDE using cmake.
I have a bunch of files in the src/ directory for the project itself and the restinio is located in src/dep/restinio/ (the version I used was the version with all the dependencies supplied)

Here are the relevant bits of my cmake file:

`#restinio
include_directories(src/dep/restinio/dev)
include_directories(src/dep/restinio/dev/asio/include)
include_directories(src/dep/restinio/dev/fmt/include)
include_directories(src/dep/restinio/dev/restinio)
include_directories(src/dep/restinio/dev/nodejs/http_parser)`

Cmake processes this without an error:
`
"C:\Program Files\JetBrains\CLion 2020.2.4\bin\cmake\win\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles" <path>
-- Configuring done
-- Generating done
-- Build files have been written to: <path>/cmake-build-debug

[Finished]
`

However, when the build command is run, something is undefined:
`
"C:\Program Files\JetBrains\CLion 2020.2.4\bin\cmake\win\bin\cmake.exe" --build <path>\cmake-build-debug --target db
[  4%] Linking CXX executable db.exe
CMakeFiles\db.dir/objects.a(db.cpp.obj): In function `ZN4asio6detail17winsock_init_base7startupERNS1_4dataEhh':
<path>/src/dep/restinio/dev/asio/include/asio/detail/impl/winsock_init.ipp:38: undefined reference to `_imp__WSAStartup@8'
CMakeFiles\db.dir/objects.a(db.cpp.obj): In function `ZN4asio6detail17winsock_init_base7cleanupERNS1_4dataE':
<path>/src/dep/restinio/dev/asio/include/asio/detail/impl/winsock_init.ipp:55: undefined reference to `_imp__WSACleanup@0'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[3]: *** [CMakeFiles\db.dir\build.make:410: db.exe] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:97: CMakeFiles/db.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:104: CMakeFiles/db.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:137: db] Error 2
`

I have tried some other ways of including the library, but none seem to work for me.

Any help would be appreciated!

**Comment by eao197** [comment]
Hi!

It seems that you have to add `wsock32` and `ws2_32` libraries to your target. See an example here: https://github.com/Stiffstream/restinio/blob/38fe6b0fe8a624bed5c6d0c9a600d0abb2db62a3/dev/cmake/sample.cmake#L17-L19

**Comment by micnekr** [comment]
Sorry for opening an issue without trying that. I managed to install a different package that was suitable for my purpose, but thank you for your time!
