### ISSUE TITLE
? not working in express_router url

### ISSUE THREAD

**Issue by noctera** [Stiffstream/restinio#139]
Sorry, it's me another time.

```
router->http_get("/signIn?username=:param", [](auto req, auto params) {
		return init_resp(req->create_response())
			.set_body(
				fmt::format(
					"Username: '{}'",
					params["param"]))
			.done();
	});
```
I am creating this Url right now, but somehow when I add ```?```, which is the GET standart, the uri can't be called anymore.
Without the ```?``` it works. For example if I use a ```&``` instead of ```?```

Thanks for advance

**Comment by eao197** [comment]
The query part of URL should be separated from the path part with `?` symbol. The query part of URL should be processed by using [`parse_query` or `try_parse_query` functions](https://stiffstream.com/en/docs/restinio/0.6/querystringparams.html).

**Comment by noctera** [comment]
I've tryed ```parse_query``` as I found in other Issues and came to this solution

```
router->http_get("/test?option1=value&option2=value", [](auto req, auto params) {
		const auto qp = restinio::parse_query(req->header().query());
		std::string username = "";
		std::string password = "";

		std::string option1 = restinio::cast_to<std::string>(qp["option1"]);
		std::string option2 = restinio::cast_to<std::string>(qp["option2"]);

		std::cout << "Option1: " << option1 << std::endl
				  << "Option2: " << option2 << std::endl;

		return init_resp(req->create_response())
			.set_body(
				fmt::format(
					"Option1: '{}'\n Option2: '{}'",
					qp["option1"],
					qp["option2"]))
			.done();
	});
```
But somehow it doesn't work yet. Could you tell me what I did wrong? Unfortunately, I can't get along with the documentation

**Comment by eao197** [comment]
Hi!

This:

```cpp
router->http_get("/test?option1=value&option2=value",
```
doesn't have a sense. It should be changed that way:

```cpp
router->http_get("/test",
```
> But somehow it doesn't work yet.

What do you expect and what do you get?

**Comment by noctera** [comment]
I expect to call the Url
```http://127.0.0.1:9000/test?option1=my_first_parameter&option2=my_second_parameter```
and want to parse the to parameters ```my_first_parameter``` and ```my_second_parameter``` on the server to use it
I could have send it in the body, but I want it to be in the query string

**Comment by eao197** [comment]
There is a very simple sample I've made from express_router_tuturial example:
```cpp
#include <iostream>

#include <restinio/all.hpp>

#include <fmt/format.h>

namespace rr = restinio::router;
using router_t = rr::express_router_t<>;

template < typename RESP >
RESP
init_resp( RESP resp )
{
	resp.append_header( "Server", "RESTinio sample server /v.0.4" );
	resp.append_header_date_field()
	.append_header( "Content-Type", "text/plain; charset=utf-8" );

	return resp;
}

auto server_handler()
{
	auto router = std::make_unique< router_t >();

	router->http_get( "/test", []( auto req, auto ){
		const auto qp = restinio::parse_query( req->header().query() );

		std::string option1 = restinio::cast_to<std::string>( qp["option1"] );
		std::string option2 = restinio::cast_to<std::string>( qp["option2"] );

		return init_resp( req->create_response() )
				.set_body(
					fmt::format( "GET of /test with: option1={}, option2={}\n",
						option1,
						option2 ) )
				.done();
	} );

	router->non_matched_request_handler(
		[]( auto req ){
			return
				req->create_response( restinio::status_not_found() )
					.append_header_date_field()
					.connection_close()
					.done();
		} );

	return router;
}

int main()
{
	try
	{
		using traits_t =
			restinio::traits_t<
				restinio::asio_timer_manager_t,
				restinio::single_threaded_ostream_logger_t,
				router_t >;

		restinio::run(
			restinio::on_this_thread< traits_t >()
				.address( "localhost" )
				.port( 9000 )
				.request_handler( server_handler() ) );
	}
	catch( const std::exception & ex )
	{
		std::cerr << "Error: " << ex.what() << std::endl;
		return 1;
	}

	return 0;
}
```
When I do a `GET` request in the form: `curl "http://127.0.0.1:9000/test?option1=my_first_parameter&option2=my_second_parameter"`
I get the expected output:

```
GET of /test with: option1=my_first_parameter, option2=my_second_parameter
```
Please note the use of double quotes in the command line, it's because `&` is a special symbol.

The same result I get when `GET` request is performed via a browser.

**Comment by noctera** [comment]
That is working. Many thanks for your help, I really appreciate it.
