### ISSUE TITLE
How to pass info from any variable in set_body?

### ISSUE THREAD

**Issue by faizol** [Stiffstream/restinio#151]
HI,

Another noob question, how can I possibly pass any information I got from a db query?
I tried something like this in the set_body method;

```
std::string test_string =" sjkdksndkjsa ";

  .set_body("<html><body>" + test_string + "</body></html>"); 
```
but I got "error while handling request: std::bad_alloc" message.

Any pointer on what is the right way to pass any dynamic info from db or anything else?

Thanks.

**Comment by eao197** [comment]
Hi!

I don't understand the problem you've described. But you can take a look at this demo project: https://github.com/Stiffstream/restinio-crud-example

**Comment by faizol** [comment]
I totally forgot about your CRUD example. That helps.

Sorry for taking your valuable time, and thank you very much. Really appreciate it.
