### ISSUE TITLE
Need help with setting bearer token in the header.

### ISSUE THREAD

**Issue by faizol** [Stiffstream/restinio#152]
Hi,

 I'm trying to set jwt token but I'm not sure if the method below is the right way to get the token from the header.

I'm setting the token like this;
```
        req->create_response()
            .append_header_date_field()
            .append_header(restinio::http_field::authorization,"Bearer "+newtoken)
            ..... 

```

and trying to read it like this;

 ```
    using namespace restinio::http_field_parsers::bearer_auth;
    const auto auth_params = try_extract_params(*req, restinio::http_field::authorization);
    if(auth_params) {
        const std::string & token = auth_params->token;
        std::cout << "token : " << token << std::endl;
    }
```
Is that the right way to get the token?

Thanks.

**Comment by eao197** [comment]
Hi! Yes, it looks like the right way.

**Comment by faizol** [comment]
Hi,

 Thanks for the reply. I can't seems to get to extract the Bearer token coz auth_params.has_value() always returns false. The auth Bearer was set and has value when I check it using http Header Live addon on Firefox.

Any pointers on how should I proceed to get the Bearer token?

Thank you very much.

**Comment by eao197** [comment]
I don't use bearer auth by myself, tools for working with this type of auth were contributed by @prince-chrismc , maybe he can help here.

Anyway, `try_parse_params` returns `expected<params_t, extraction_error_t>`. If you can't get the `params_t` then you can examine `extraction_error_t` instance. Maybe it provides some useful information.

**Comment by faizol** [comment]
Thank you very much.
I think I have found my problem. The token should be refreshed when navigating from one page to another as the token is not persistent, right? So if the previous page doesn't set the token in the header, then it won't be read by the next page. But I will contact @prince-chrismc to confirm what I mentioned above is the problem.

Another question. What's the best way to redirect a page to another page from within restinio? What I do now is to embed javascript in a body response. 

Thank you again for your time, cheers.

**Comment by faizol** [comment]
I'll close this for now, thank you again.

**Comment by eao197** [comment]
> What's the best way to redirect a page to another page from within restinio?

What do you mean under "redirect a page"? The use of HTTP Status Code 30x, like 301 "Moved Permanently"?

**Comment by faizol** [comment]
Thanks for the 301 http response info.
I have a question about using restinio. I really like this library, as it's very performant. Also it's not too hard to get around the library, though it still takes some time to familiarize with it. My question is more about the general workflow in using this awesome library, like a "best practice" guide (which applicable to small scale projects like the CRUD example) that should a noob like me be following if using this library?
The CRUD example was helping a lot in studying about this library, but probably a bit more of documentation can help users to really integrate this library in a large scale project (which would include a large portion of interacting or managing the client side), especially so when this library is truly scalable in managing all the functionality of a web server?

I have a question about the best practice on managing users login to the system using database through this library. What's the best options that a user should use that is provided by this library to manage the users? This is actually more of a workflow rather than about this library, but by highlighting the readily available functionalities in the library, that alone will make this library be very user friendly towards new user.

Btw, many thanks for developing this library, I really appreciate it.

Cheers,

**Comment by prince-chrismc** [comment]
![image](https://user-images.githubusercontent.com/16867443/132689006-f548e219-befa-4567-a4a6-41c4f3e40996.png)

Some note how I implemented the client workflow, 

- a GET endpoint which sends the user to the "form submission"
   - returns 301 to the auth service (fills in callback uri)
   - backend gets a token on the users behalf

- All other endpoints use the code in https://github.com/Stiffstream/restinio/issues/152#issue-991363698
   - I use https://github.com/Thalhammer/jwt-cpp for working with JWT (shameless plug)
   - Plus I have special application logic

**Comment by prince-chrismc** [comment]
> The token should be refreshed when navigating from one page to another as the token is not persistent, right? So if the previous page doesn't set the token in the header, then it won't be read by the next page

According to best practices, you should save the JWT securely in the application... which has a short expiration and you only need to refresh at the half life =)
