### ISSUE TITLE
Current version does not compile with fmt dependency

### ISSUE THREAD

**Issue by fentonscode** [Stiffstream/restinio#156]
The current snapshot of RESTinio fails compilation with multiple instances of:

`Error	C2338	Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt`

which would appear to indicate that the template code is not complete. Changing this to `std::format` and moving the language level to C++20 did not help either, as the types could not be coerced into C-style strings. Unfortunately this prevents running the hello world example, let alone anything else.

I have not yet investigated whether there were there changes to `fmt` that might have caused this.

**Dependencies used**

ASIO 1.22.1
fmt 8.1.1
http-parser 2.9.4

**Environment**

- Compiler IDE: Visual Studio 2019
- OS: W10 Enterprise

**Comment by eao197** [comment]
Hi!

I can't reproduce that problem.

There is the result of compilation with Visual Studio 2019 in C++17 mode:
```
restinio.github\dev>ruby sample\hello_world\prj.rb
include dirs:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include
  C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt
  C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared
  C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um
  C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt
  C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
Compiling nodejs/http_parser_mxxru/../../nodejs/http_parser/http_parser.c ...
http_parser.c
Building target/cpp17/vc16_0_19_29_30140_x64/release/lib/hodejs_http_parser.lib ...
Compiling sample/hello_world/main.cpp ...
main.cpp
Building target/cpp17/vc16_0_19_29_30140_x64/release/sample.hello_world.exe ...
```

And there is the result with Visual Studio 2022 in C++17 mode:
```
restinio.github\dev>ruby sample\hello_world\prj.rb
include dirs:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\ATLMFC\include
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include
  C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt
  C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared
  C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um
  C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt
  C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt
Compiling nodejs/http_parser_mxxru/../../nodejs/http_parser/http_parser.c ...
http_parser.c
Building target/cpp17/vc17_0_19_31_31104_x64/release/lib/hodejs_http_parser.lib ...
Compiling sample/hello_world/main.cpp ...
main.cpp
Building target/cpp17/vc17_0_19_31_31104_x64/release/sample.hello_world.exe ...
```

There are also no problems under Ubuntu 20.04 with GCC 9.4 and 11 in C++17 mode, and GCC 11 in C++20 mode.

Asio 1.22.1 and fmt 8.1.1.

Maybe some addition FMT-related flags are turned on for your project.

**Comment by fentonscode** [comment]
Thanks for looking into this, perhaps it's down to how the dependencies have been entered at my end. My steps were:

1. Download ASIO 1.22.1, point MSVS at the `asio/include` dir
2. Download fmt 8.1.1, point MSVS to the `fmt/include/fmt` dir
3. Download http-parser 2.9.4, add the .h and .c file to the build process
4. Download RESTinio source
5. Create a project for the hello world example in VS2019 (include dirs as above)

When it initially failed I also tried stripping the fmt folder back to a single dir with all the .h and .cc files in one place (as the .cc is an amalgamated collection of the headers), but this didn't change anything.

There are no compilation errors in the RESTinio inclusions for ASIO and fmt, so I assume it's finding the code, but for some reason not generating all of the templates. Due to the tangling of other libraries I can't make use of the package managers at the moment, so it's likely there's a config somewhere that needs to be highlighted for manual builds?

**Comment by eao197** [comment]
I think the simplest way is to download a full archive from the [latest release](https://github.com/Stiffstream/restinio/releases/tag/v.0.6.14) and then follow [instructions for CMake](https://stiffstream.com/en/docs/restinio/0.6/obtaining.html#cmake). If you want the latest versions of Asio and FMT then you can replace the corresponding folders after unpacking the archive.

If you collect dependencies by yourself then check the definitions that necessary for building (see [here](https://stiffstream.com/en/docs/restinio/0.6/obtaining.html#dependencies-default-settings)).

For example, there is a command line for building on Linux (see -D parameters):
```
g++ -c -o target/cpp17/_objs/sample_hello_world/main.o 
 -Wextra -Wall -Wno-noexcept-type -O2
 -DNDEBUG
 -DASIO_HAS_STD_CHRONO
 -DASIO_STANDALONE
 -DASIO_DISABLE_STD_STRING_VIEW
 -DHTTP_PARSER_STRICT=0
 -DFMT_HEADER_ONLY
 -I. -Iclara -I./asio/include -Inodejs/http_parser -Ifmt/include -fPIC -std=c++17 sample/hello_world/main.cpp
```

**Comment by fentonscode** [comment]
Ah thanks I'd missed the FMT_HEADER_ONLY symbol, I think that's cured it!
