### ISSUE TITLE
Upgrade Catch2 to v3

### ISSUE THREAD

**Issue by eao197** [Stiffstream/restinio#158]
Catch2 library is used as unit-test framework in the RESTinio development.

Since v3 Catch2 is no more header-only library: https://github.com/catchorg/Catch2/releases/tag/v3.0.1

RESTinio have to be updated to Catch2 after Catch2-v3 will be stabilized and got a few correcting releases.

**Comment by barracuda156** [comment]
And currently tests fail due to non-existent header:
```
fatal error: catch2/catch.hpp: No such file or directory
    5 | #include <catch2/catch.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
Correct name is `catch_all.h`.

**Comment by eao197** [comment]
It seem that we can't add support for Catch2-v3 for CMake and MxxRu: Catch2-v3 requires generation of catch_user_config.hpp from catch_user_config.hpp.in during the configure phase. This is simply not possible with MxxRu.

So we have to drop MxxRu support.

It's not a problem. But I'm afraid we can't do that in 0.6 branch. So the support for Catch2-v3 will wait until the work on 0.7 branch will be started :(

**Comment by eao197** [comment]
Catch2 v3 is used since v.0.7.0.
