### ISSUE TITLE
The installed file include/restinio/so5/so_timer_manager.hpp uncludes the header so_5/all.hpp that isn't installed

### ISSUE THREAD

**Issue by yurivict** [Stiffstream/restinio#175]
This happens when the project is configured with:

-DRESTINIO_SAMPLE:BOOL=true -DRESTINIO_INSTALL_SAMPLES:BOOL=true -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/disk-samsung/freebsd-ports/www/restinio/work/Clara-2bfd8b2/include  -I/disk-samsung/freebsd-ports/www/restinio/work/json_dto-9a08aaa/dev -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/disk-samsung/freebsd-ports/www/restinio/work/Clara-2bfd8b2/include  -I/disk-samsung/freebsd-ports/www/restinio/work/json_dto-9a08aaa/dev -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/disk-samsung/freebsd-ports/www/restinio/work/Clara-2bfd8b2/include  -I/disk-samsung/freebsd-ports/www/restinio/work/json_dto-9a08aaa/dev -isystem /usr/local/include  -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING="  -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_MODULE_LINKER_FLAGS:STRING="  -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_SHARED_LINKER_FLAGS:STRING="  -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DRESTINIO_FIND_DEPS:BOOL=ON -DRESTINIO_USE_EXTERNAL_HTTP_PARSER:BOOL=ON -DRESTINIO_USE_EXTERNAL_SOBJECTIZER:BOOL=ON -DRESTINIO_BENCH:BOOL=OFF -DRESTINIO_INSTALL_BENCHES:BOOL=OFF -DRESTINIO_TEST:BOOL=OFF -GNinja

**Comment by eao197** [comment]
I'm sorry for that, but I don't understand what is going on and I'm afraid I can't help here.
