### ISSUE TITLE
express_router errors

### ISSUE THREAD

**Issue by jm130794** [Stiffstream/restinio#2]
Hello,

We are testing Restinio 0.4.1 and we have a problem with the express_router_tutorial example.
When we use the URL http://localhost:8080/many/2018.06.01, the route used is non_matched_request_handler.
For the other requests, everything works correctly.

Jean-Marc

**Comment by eao197** [comment]
Hi!

Thanks for your report, we will investigate the case.
Can you provide some more information about your compiler and OS?

**Comment by eao197** [comment]
Do you really use POST method? May be you use GET (for example producing request via Web-browser).

If a request is made this way:
~~~~~{.sh}
curl -X POST -d "example" http://localhost:8080/many/2018.06.01
~~~~~
then it works as expected:
~~~~~
POST request with many parameters:
year: 2018
month: 06
day: 01
body: example
~~~~~

**Comment by jm130794** [comment]
You're right. You're right. We made a mistake using the GET method. Sorry...
Restnio is a really nice tool.

Thank you
