### ISSUE TITLE
CMake configure fails when using boost asio via find

### ISSUE THREAD

**Issue by rcane** [Stiffstream/restinio#201]
There are two bugs in the cmake scripts when using boost asio (`RESTINIO_ASIO_SOURCE=boost` and `RESTINIO_DEP_BOOST_ASIO=find`).

The first one is this [line](https://github.com/Stiffstream/restinio/blob/1f95dbc72b94b575d1b860f569fe85511a1fff15/dev/CMakeLists.txt#L151C9-L151C62) in the CMakeLists.txt file.
The `COMPONENTS` part of `find_package` is only supposed to refer to libraries that are being linked. Since 'headers' is a header-only library it cannot be linked. Having it in the `COMPONENTS` list will make the cmake configuration fail since there is no target for the 'headers' library.
To fix this just remove the 'headers'  reference. The include directory for those header files will already be configured with the `find_package(Boost REQUIRED)` line.

The second bug is in [dev/restinio/cmake/restinio-config.cmake.in](https://github.com/Stiffstream/restinio/blob/1f95dbc72b94b575d1b860f569fe85511a1fff15/dev/restinio/cmake/restinio-config.cmake.in#L19) where "boost" is misspelled. It should say "Boost" instead.

**Comment by eao197** [comment]
Hi, @rcane !

Thanks for reporting! We'll take a look at them a bit later.

**Comment by eao197** [comment]
I've added a [new Dockerfile](https://github.com/Stiffstream/restinio-dockerfiles/blob/f221fbe2606bf69dc1618a285fc5940bce525c4c/v0.7/archlinux-gcc-find-boost-asio.Dockerfile) to check the presence of the first problem on Linux. Unfornunately, this file doesn't show an error with CMake configure.

I'll try to find another way to show that such a problem exists and that it will be fixed properly.

**Comment by eao197** [comment]
I'm trying to check that behaviour on Windows with Boost. Maybe it will show the problem.

**Comment by ngrodzitski** [comment]
@eao197  
Since v0.7.0 we have boost-asio ci (both system and prebuild=`kindly build from sources by @MarkusJx`). So I don't think dockerfile is necessary:
[Ubuntu-22.04 (gcc-9, Debug, C++17, boost-system-package asio)](https://github.com/Stiffstream/restinio/actions/runs/6849919339/job/18623071806#logs)
[Ubuntu-22.04 (gcc-12, Release, C++20, boost asio)](https://github.com/Stiffstream/restinio/actions/runs/6849919339/job/18623073069#logs)

Regarding windows and vcpkg I can take a look tomorrow, and since github runners by default have vcpkg in it we can think of I  adding a CI (win+vcpk) to avoid such issues future.

**Comment by eao197** [comment]
@ngrodzitski 

I had used Dockerfiles before you've configured GitHub CI for v0.7, but the Dockerfile used `RESTINIO_DEP_BOOST_ASIO=system`. The new file uses `RESTINIO_DEP_BOOST_ASIO=find`.

I hope I can check Boost on Window today (without vcpkg).

**Comment by eao197** [comment]
I've repeated this problem with help of https://github.com/Stiffstream/restinio-crud-example/tree/restinio-0.7.0-vcpkg-overlay-boost-asio

There is a fix for the problem in the 0.7-dev-issue-201 branch (at the commit 1f0234d06563a5b060e2435dbf8fdb1e50dc6e2e).

I think this fix will be a part of upcoming 0.7.1 release, but I'm afraid this may not happen on this week.
