### ISSUE TITLE
build system regression: RESTINIO_USE_EXTERNAL_SOBJECTIZER no longer available

### ISSUE THREAD

**Issue by Apteryks** [Stiffstream/restinio#207]
Hello!

There used to be in 0.6 the RESTINIO_USE_EXTERNAL_SOBJECTIZER CMake option to allow using a system provided sobjectizer library; that appears to have been removed with 0.7, and it doesn't seem possible anymore to select a system version to use instead of the bundled (source) copy.

Thank you!

**Comment by eao197** [comment]
Hi!

The branch 0.7-dev-0.7.2-issue-208 is no contains a version that supports `RESTINIO_DEP_SOBJECTIZER` option for CMake.

It has three available values:

* `local`, as usual, the source code of SObjectizer is expected to be in the source tree;
* `find`, the CMake's `find_package` will be used. It's expected that SObjectizer is compiled and installed somewhere via CMake;
* `system`. It's expected that SObjectizer is installed in the system by using system's package manager.

If `RESTINIO_DEP_SOBJECTIZER` is `system` the `RESTINIO_SOBJECTIZER_LIB_LINK_NAME` has to be specified manually. An example can be seen [here](https://github.com/Stiffstream/restinio-dockerfiles/blob/cdcd67bfaf3b8b1bb493ef80c0673645eb6fd777/v0.7/archlinux-gcc-system-sobjectizer.Dockerfile#L53-L55).

**Comment by Apteryks** [comment]
Tested fine with `-DRESTINIO_DEP_SOBJECTIZER=find` after updating sobjectizer to 5.8.2. Thanks!
