### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by alexv-ds** [Stiffstream/restinio#210]
I'm compiling the express_router example and one main.cpp file took 30 seconds to compile.

```
real 0m37.997s
user 0m36.830s
sys 0m1.126s
```

Is it possible to speed this up in any way?

**Comment by eao197** [comment]
Hi!

RESTinio makes heavy use of C++ templates and this leads to long compilation times.

However, 37s looks terrible. I can suppose that you have to use old hardware. Because on my laptop with not a modern i5 8265U it takes only 15s (Kubuntu 22.04, GCC 11.4):

```
$ touch ../sample/express_router_tutorial/main.cpp
$ time cmake --build . --config Release --target sample.express_router_tutorial
[2/2] Linking CXX executable bin/sample.express_router_tutorial

real    0m15,014s
user    0m14,626s
sys     0m0,386s
```
