### ISSUE TITLE
Question: How to get http_server_t<> address

### ISSUE THREAD

**Issue by saukijan** [Stiffstream/restinio#215]
Hello everyone, 

Is there a way to get the IP address and port of the `http_server_t<>` after it is constructed? I am using `on_pool_runner_t<>` to retain access to my  `http_server_t<>` and allow me to start/stop the server.

**Comment by eao197** [comment]
Hi!

You can try to use [acceptor_post_bind_hook](https://stiffstream.com/en/docs/restinio/0.7/contextentities.html#post-bind-hook-for-the-acceptor).
