### ISSUE TITLE
server side connection timeout ?

### ISSUE THREAD

**Issue by hassan379** [Stiffstream/restinio#224]
Thank you for this great library.
Does this library support connection timeouts on server side?
I have a function that can run for a long time depending on the passed parameters.
Does the server cancel the request and throw an exception or error that can be handled to send a proper response after a specific time?
Thanks in advance.

**Comment by eao197** [comment]
Hi, @hassan379 

RESTinio supports timeouts by default. There is `handle_request_timeout` setting's parameters that controls how long a handler can work (you can find [it in the "settings" section](https://stiffstream.com/en/docs/restinio/0.7/serversettings.html#handle-request-timeout)).

But take into account the [threading model of RESTinio](https://stiffstream.com/en/docs/restinio/0.7/threadingmodel.html). If you handle you request in a synchronous maner, then the RESTinio doesn't have ability to break a connection if the timeout elapsed.
