### ISSUE TITLE
sendfile() opens the file exclusively under Windows

### ISSUE THREAD

**Issue by rcane** [Stiffstream/restinio#25]
The `::CreateFileA` used to open the file for `sendfile` does not have the `FILE_SHARE_READ` option set. This means that the file is opened exclusively and the next attempt to open the file will fail until the sendfile operation has finished and the handle is closed.

**Comment by eao197** [comment]
You can try now the version from Master branch.

**Comment by rcane** [comment]
Works.

Btw, would you like me to close my open issues when I think they are fixed?

**Comment by eao197** [comment]
> Works.

Great news!

> Btw, would you like me to close my open issues when I think they are fixed?

Yes.
