### ISSUE TITLE
Logging redirecting

### ISSUE THREAD

**Issue by binarytrails** [Stiffstream/restinio#27]
Hi devs,

As I'm finishing the integration of RESTinio as a proxy server, I'm wondering how would I properly redirect the logging using the ```restinio::traits_t``` or perhaps, another way that you would suggest?

Basically, we have our own logger, and I would like to redirect it to the same one to avoid clashing and format a little bit the output to be standard to ours.

Cheers,
Seva

**Comment by eao197** [comment]
IIRC, I described this case in [that article](https://habr.com/ru/post/417527/).
