### ISSUE TITLE
both ipv4 & ipv6 support at runtime

### ISSUE THREAD

**Issue by binarytrails** [Stiffstream/restinio#30]
Is the IPV6 supported or is it planned to be supported in a near future?

Thank you!

**Comment by eao197** [comment]
> Is the IPV6 supported

Supported. See [server's setting chapter](https://stiffstream.com/en/docs/restinio/0.4/serversettings.html).

**Comment by binarytrails** [comment]
@eao197 oh yes I saw this actually, I'm doing the same for the client but I mean at runtime because these settings are set before running the restinio main loop. Does RESTinio support both at runtime? Because I had trouble figuring out why it only accepts ipv4 or ipv6 connections once started

**Comment by binarytrails** [comment]
I saw that you can do ip version independent with restinio::asio_ns
https://www.boost.org/doc/libs/1_42_0/doc/html/boost_asio/reference/ip__address.html

**Comment by eao197** [comment]
To create `asio::ip::tcp::endpoint` we should specify a protocol. The corresponding fragment is [here](https://github.com/Stiffstream/restinio/blob/beb29032c575f668a15edb9a2886ee363400e26a/dev/restinio/impl/acceptor.hpp#L150-L161). Protocols is being got from server settings ([by default it is ipv4](https://github.com/Stiffstream/restinio/blob/beb29032c575f668a15edb9a2886ee363400e26a/dev/restinio/settings.hpp#L331)), but can be changed to ipv6.

**Comment by binarytrails** [comment]
@eao197 so both are not supported simultaneously at runtime? you can only start in ipv4 or ipv6, right?

**Comment by eao197** [comment]
I think your question is not related to RESTinio, but to Asio: https://stackoverflow.com/questions/31125229/accept-ipv4-and-ipv6-together-in-boostasio

**Comment by binarytrails** [comment]
Oh well, I guess it could be simply said that one does not have to set ```settings.address``` and set ```settings.protocol(restinio::asio_ns::ip::tcp::v6())``` as said in your link: 

> If you create a IPv6 acceptor, it will accept both IPv4 and IPv6 connections if IPV6_V6ONLY socket option is cleared.

Which is the case by default in RESTinio. Thanks!
