### ISSUE TITLE
Async TLS client code sample

### ISSUE THREAD

**Issue by davidskiff** [Stiffstream/restinio#4]
Hi,
I would like to try your elegnant C++ REST library on Linux.
I read the documentation + test cases, but i couldnt find async TLS client implementation.
May u please refer me to relevant documentation or code snippet?

Thanks,
David.

**Comment by eao197** [comment]
Hi!

RESTinio implements only HTTP-server, there is no HTTP-client functionality in RESTinio at this moment.

**Comment by davidskiff** [comment]
OK, thx for quick reply
