### ISSUE TITLE
Some alerts

### ISSUE THREAD

**Issue by Milerius** [Stiffstream/restinio#46]
Hello reading code through a tool let me know about an alert in code, i share it with you:

missing const ref parameters or std::move:

(restinio/impl/connection_settings.hpp)
<img width="1197" alt="Capture d’écran 2019-08-17 à 11 00 23" src="https://user-images.githubusercontent.com/21139416/63209226-6027bb00-c0de-11e9-97c0-554dd526195c.png">

**Comment by eao197** [comment]
Hi, Roman!

Thanks for reporting this, but I don't see a problem here. An instance of `connection_setting_t` is created only once per HTTP-server. An incoming `parser_settings` object is a temporary and (I suppose) can be eliminated by the compiler. Anyway `http_parser_settings` is a POD C struct for that move operation has no significant effect.

**Comment by Milerius** [comment]
Ok no problem, i just share it with you sometimes it's can be helpfull

**Comment by eao197** [comment]
Yes, thank you for your attention to the details.
