### ISSUE TITLE
How do you disable logging?

### ISSUE THREAD

**Issue by Git-Curve** [Stiffstream/restinio#52]
Title says it

**Comment by eao197** [comment]
If you take a look at the definition of [default_traits_t](https://github.com/Stiffstream/restinio/blob/v.0.6.0/dev/restinio/traits.hpp#L157) or [default_single_thread_traits_t](https://github.com/Stiffstream/restinio/blob/v.0.6.0/dev/restinio/traits.hpp#L174-L176) you'll see usage of `null_logger_t` type. If that type is used in server traits then RESTinio doesn't log anything.

So if you don't need logging then use `restinio::null_logger_t` in your server's traits or use `restinio::default_traits_t` or `restinio::default_single_thread_traits_t` as traits type for your server.
