### ISSUE TITLE
How to upload files

### ISSUE THREAD

**Issue by VincenzoLaSpesa** [Stiffstream/restinio#56]
Hello.
Is there any sample or documentation about how to handle files uploaded from the client?

**Comment by eao197** [comment]
Hi!
No. There isn't such an example yet.

**Comment by eao197** [comment]
Hi!
We've added some new functionality into RESTinio and implemented [file_upload example](https://github.com/Stiffstream/restinio/tree/267ec66dfe6484d67fa35350fa49b353e1ce88cd/dev/sample/file_upload). This will be a part of upcoming v.0.6.1 release (I hope we can roll this release out this week).

**Comment by eao197** [comment]
The [file_upload example](https://github.com/Stiffstream/restinio/blob/v.0.6.1/dev/sample/file_upload/main.cpp) is now the part of RESTinio.
