### ISSUE TITLE
m_write_groups.erase() is noexcept in MSVC

### ISSUE THREAD

**Issue by ahmedyarub** [Stiffstream/restinio#64]
Right here you can see the change:
https://github.com/Stiffstream/restinio/commit/7ab2fd3551d413e960cf831ef6dc285eeac2642f#diff-014dfa4235c0e34420ccb97dba6181d7R97

I had to comment this macro out for the compilation to proceed. It looks like the vector header that ships with Visual Studio 2019 defines erase() as a noexcept.

**Comment by eao197** [comment]
Which version of VC++ do you use?

Mine is 19.22.27905.

**Comment by eao197** [comment]
I've updated VisualStudio 2019 to 16.3.10 (VC++ version is 19.23.28107), and there is no compilation error (in C++14 and C++17 modes).

**Comment by ahmedyarub** [comment]
I'm using MSVC 14.24.28314 which comes with Visual Studio Enterprise 2019 Preview Version 16.4.0 Preview 6.0. You can see the function definition with noexcept here:
https://github.com/microsoft/STL/blame/8f4c8163775d665d80642044ce27c4bc696127ce/stl/inc/vector#L1341

**Comment by eao197** [comment]
I've merged a fix into master branch. Can you check it with your VC++ compiler?

**Comment by ahmedyarub** [comment]
worked like a charm thank you!

**Comment by eao197** [comment]
Thanks for reporting this issue.
