### ISSUE TITLE
Anyway to parse POST BODY?

### ISSUE THREAD

**Issue by zhangzq** [Stiffstream/restinio#78]
I'm looking for utility to parse body of post request, but found nothing in document.

**Comment by eao197** [comment]
Content of POST's body depends on `content-type` HTTP-field. Different types of data have different representations.

If you're speaking about parsing the content of HTML form in POST's body then it depends on the value of `content-type` as described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST):

* in the case of `application/x-www-form-urlencoded` you can try to use `restinio::parse_query` or `restinio::try_parse_query` with `x_www_form_urlencoded` trait;
* in the case of `multipart/form-data` you can try to use HTTP-field helpers like [detect_boundary_for_multipart_body](https://github.com/Stiffstream/restinio/blob/v.0.6.5/dev/restinio/helpers/multipart_body.hpp#L480-L500) + [split_multipart_body](https://github.com/Stiffstream/restinio/blob/v.0.6.5/dev/restinio/helpers/multipart_body.hpp#L38-L75), or [enumerate_parts](https://github.com/Stiffstream/restinio/blob/v.0.6.5/dev/restinio/helpers/multipart_body.hpp#L628-L704). See also [content-disposition](https://github.com/Stiffstream/restinio/blob/v.0.6.5/dev/restinio/helpers/http_field_parsers/content-disposition.hpp#L438-L454) helper.

**Comment by eao197** [comment]
@zhangzq 
Can this issue be closed?
