### ISSUE TITLE
Using restinio as http client

### ISSUE THREAD

**Issue by atari83** [Stiffstream/restinio#88]
Hello there,
Please excuse me for this basic question, Could restinio be used as http client ?
My case is to expose a http server to process incoming requests, but also my application has to generate some requests to different web servers as well.

Thanks

**Comment by eao197** [comment]
No, RESTinio is server-only library.

As an example of the usage of RESTinio for receiving of incoming HTTP requests and libcurl for issuing of outgoing requests, you can see [this post](https://eao197.blogspot.com/2018/03/progc-async-processing-of-incoming-and.html).

**Comment by atari83** [comment]
Great, thank you very much :)
