### ISSUE TITLE
dependencies on Linux

### ISSUE THREAD

**Issue by briandgr** [Stiffstream/restinio#90]
Hi,

Install of restinio on windows was a breeze through vcpkg, now I'm trying to get restinio installed on Centos8.

Can you please provide some more guidance on the below.
I have downloaded github.com/nodejs/http-parser 
how can I have it recognised by cmake as the  "unofficial-http-parser"  ?

CMake Error at CMakeLists.txt:74 (find_package):
  Could not find a package configuration file provided by
  "unofficial-http-parser" with any of the following names:

    unofficial-http-parserConfig.cmake
    unofficial-http-parser-config.cmake

thanks,

**Comment by eao197** [comment]
Hi!

I think you can try to use RESTinio on Linux via vcpkg too. There is an example that is built on Windows/Linux via vcpkg: https://github.com/Stiffstream/restinio-crud-example

If not then try to install libhttp-parser via Centos's package manager and configure RESTinio with `RESTINIO_USE_EXTERNAL_HTTP_PARSER` option set to `ON` (see [here](https://stiffstream.com/en/docs/restinio/0.6/obtaining.html#cmake) for more details).
