### ISSUE TITLE
Bearer auth parser

### ISSUE THREAD

**Issue by prince-chrismc** [Stiffstream/restinio#95]
Totally got myself backwards with too many RFCs open

Unfortunately I followed [RFC 6749](https://tools.ietf.org/html/rfc6749#section-2.3.1) instead of my intended [RFC 6750](https://tools.ietf.org/html/rfc6750#section-2.1) which are not the same "authorization request header" scheme. 

I'll open a PR with the fix shortly. I apologize for the inconvenience.

**Comment by eao197** [comment]
Thanks for your fix.

It'll be a part of the upcoming v.0.6.8.

I've added a few more overloads for `try_extract_params` functions in `http_field_parsers::basic_auth` and `http_field_parsers::bearer_auth` namespaces.

There is also a new helper `try_parse_field`.

If there won't be any new fixes or new ideas I'll release v.0.6.8 tomorrow morning.

**Comment by prince-chrismc** [comment]
Nothing further on my end, I am **very** happy with RESTinio :smile:

**Comment by eao197** [comment]
> I am very happy with RESTinio

I'm glad to hear this!

**Comment by eao197** [comment]
Fixed in v.0.6.8.
