### ISSUE TITLE
Please fix CRLF brokenness in your library

### ISSUE THREAD

**Issue by ned14** [Stiffstream/restinio#97]
The current inconsistent CRLF makes it painful to use restinio from Linux and Windows off a Samba share.

Here is a suitable `.gitattributes` to use to ensure broken CRLF never happens again: https://github.com/ned14/restinio/blob/Branch_v.0.6.1.1/.gitattributes

Instructions are here for repairing your existing repo:
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

My thanks in advance.

**Comment by eao197** [comment]
I've tried. The result is now in 0.6-dev branch.

**Comment by ned14** [comment]
That's really great, thank you. You've reduced down my cmake hunter restinio package fork delta now to merely this: https://github.com/Stiffstream/restinio/compare/master...ned14:master

Do you have any objections to your next release being submitted to cmake hunter?

**Comment by eao197** [comment]
> Do you have any objections to your next release being submitted to cmake hunter?

No.
